name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_NAME: travelless/travelless.github.io
          BRANCH: master # The branch the action should deploy to.
          FOLDER: docs/.vitepress/dist # The folder the action should deploy.
          # deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          # branch: master
          # folder: docs/.vitepress/dist
          