name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i yarn -g
      - run: yarn install --frozen-lockfile
      - run: echo ${{ secrets.VITE_TEST_SECTET }} > .env

      - name: Build
        run: yarn build
        env: 
          VITE_TEST_SECTET: ${{ secrets.VITE_TEST_SECTET }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG_TOKEN }}
          publish_dir: docs/.vitepress/dist
          cname: firstmeet.store
